### ISSUE TITLE
the timing of the effect type really effecting the value.

### ISSUE THREAD

**Issue by LemonHX** [dannypsnl/eikyo#18]
Currently, our type check strategy for the timing of adding effect is pre-function, that's why we could make the ownership system. As following

```rs
fn f(x : T -owned, y : T -owned) -> ()

f(a, a)
  ^
  We would like to remove `a`'s `owned` at this place
     ^
     Then here will get the type check error
```

Now take into consideration if we doing the following things related to `sort` effect.

for instance, if we have a function `f` and `g`
with type

```rs
fn f(a : list<a> +sort, g : fn(list<a> sort) -> b) -> b
```

the end user could call this function with

```rs
f(a, g(a))
```

but the problem is when we add the effect to the value pre-function-ly, the `g` function passes the type check with receiving an unsorted variable `a`, which could cause panic, but if we are trying to do it pos-function-ly, the `g` will not work which is expected, but the ownership system also doesn't work.

**Comment by dannypsnl** [comment]
### post-affect

A potential solution based on post-affect is for the following instance

```rs
fn f(a : t -owned, b : t -owned) -> b
```

Found the result is `owned -owned -owned`, which derives `-owned`, a negative type will get rejected. But consider

```rs
fn f (a : t -owned, b : t +owned) -> b
```

post-affect has more problems that have to consider.

### pre-affect

Another potential solution is recognizing the pattern that an expression is trying to modify its mark but also trying to use to pass some gate at the same time.

This requires we make a scope for function call checking, for instance:

```rs
fn g : (x : list<a> ordered) -> M
fn f(x : list<a> +ordered, y : M) -> M

f(a, g(a))
```

When expanding(type checking) `f`, we make a scope
```
f(
  checking a
  checking g(a)
)
```
In the same scope, since `g(a)` is trying to use `a`'s `ordered` immediately, this makes an error.

However, the solution seems really hard to implement.

**Comment by dannypsnl** [comment]
Another potential solution is recognizing the pattern that an expression is trying to modify its mark but also trying to use to pass some gate at the same time.

**Comment by dannypsnl** [comment]
these should basically reconsidered in https://github.com/dannypsnl/violet, here will be archived
